[package]
name = "ul-consensus"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
num-bigint = { version = "0.4", features = ["serde"] }
num-traits = "0.2"
serde = { version = "1", features = ["derive"] }
ul_types = { package = "ul-types", path = "../ul-types" }
ul_ledger = { package = "ul-ledger", path = "../ul-ledger" }
